name: Web Traffic Pipeline

on:
  schedule:
    - cron: "0 0 * * *"  # Schedule: Runs daily at midnight UTC
  workflow_dispatch:      

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pipeline
      run: ./run_pipeline.sh
